import base64
import codecs

from Crypto.Util.number import long_to_bytes

a = "MIIDczCCAlugAwIBAgIJALJNrvJUaHLaMA0GCSqGSIb3DQEBCwUAMC8xDjAMBgNVBAoTBVN1cmdlMR0wGwYDVQQDExRhY3RpdmF0aW9uLnN1cmdlLnJ1bjAeFw0xNjA2MjgxMjI5MDVaFw0yNjA2MjYxMjI5MDVaMC8xDjAMBgNVBAoTBVN1cmdlMR0wGwYDVQQDExRhY3RpdmF0aW9uLnN1cmdlLnJ1bjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKFg"
print(base64.b64decode(bytes(a,'utf-8')))
